apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: apps
    repoURL: 'https://github.com/Miekus/Portfolio-GitOps.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true