apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-store

  target:
    name: external-secret
    creationPolicy: Owner

  data:
  - secretKey: mysql-host
    remoteRef:
      key: mysql-host
  - secretKey: mysql-user
    remoteRef:
      key: mysql-user
  - secretKey: mysql-uri
    remoteRef:
      key: mysql-uri
  - secretKey: mysql-password
    remoteRef:
      key: mysql-password