apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "41573f07-0064-492e-970c-894fd95bce25"
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://mk-keyvault.vault.azure.net/"
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          name: MK-Azure-Secret-sp
          key: ClientID
        clientSecret:
          name: MK-Azure-Secret-sp
          key: ClientSecret
