apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/Miekus/Portfolio-GitOps.git
    targetRevision: HEAD
    path: charts/elasticsearch
  destination:
    server: https://kubernetes.default.svc
    namespace: default