apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/VinnieVenture/Flask_website.git
    targetRevision: devops
    path: mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: default