apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mysql
    repoURL: https://github.com/VinnieVenture/Flask_website.git
    targetRevision: HEAD