apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: "nginx" 
      acme.cert-manager.io/http01-edit-in-place: "true"
  name: ingress
spec:
  tls:
  - hosts:
    - testmk.ddns.net
    secretName: letsencrypt-tls
  rules:
  - host: testmk.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: flaskapp-service
            port:
              number: 80