# # This is a SecretProviderClass example using system-assigned identity to access your key vault
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-sync
# spec:
#   provider: azure
#   secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
#   - data:
#     - objectName: mysql-user                       
#       key: mysql-user                          
#     - objectName: mysql-uri                       
#       key: mysql-uri                          
#     - objectName: mysql-host                       
#       key: mysql-host                          
#     - objectName: mysql-password                        
#       key: mysql-password                          
#     secretName: mysql-secrets                     
#     type: Opaque  
#   parameters:
#     usePodIdentity: "false"
#     useVMManagedIdentity: "true"    # Set to true for using managed identity
#     userAssignedIdentityID: 201da437-31c6-4abf-bfd1-e56750ac841c      # If empty, then defaults to use the system assigned identity on the VM
#     keyvaultName: "MK-KeyVault"
#     tenantId: 41573f07-0064-492e-970c-894fd95bce25            
#     objects:  |
#       array:
#         - |
#           objectName: mysql-user
#           objectType: secret       
#         - |
#           objectName: mysql-uri
#           objectType: secret        # object types: secret, key, or cert
#         - |
#           objectName: mysql-password
#           objectType: secret       
#         - |
#           objectName: mysql-host
#           objectType: secret       
               